name: AutoCityBuilder
main: io.github.densyakun.bukkit.autocitybuilder.AutoCityBuilder
version: 1.0
author: Densyakun
website: http://densyakun.github.io/

commands:
  osm:
    description: Build from OSM.
    permission: autocitybuilder.command.osm

permissions:
  autocitybuilder.*:
    children:
      autocitybuilder.command: true
      autocitybuilder.command.osm: true
  autocitybuilder.command:
    default: true
  autocitybuilder.command.osm:
    default: op